[package]
name = "ext-examples-command-pattern-multi-threaded"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
spaik = { path = "../.." }
