[package]
name = "spaik"
version = "0.1.0"
authors = ["Jonas Møller <jonas@nimda.no>"]
description = "A Lisp"
readme = "README.org"
edition = "2018"
repository = "https://github.com/snyball/spaik"
homepage = "https://github.com/snyball/spaik"
license = "BSD-2-Clause"

[profile.release]
#lto = "fat"
#codegen-units = 1
#panic = "abort"

[features]
default = ["repl", "lisp-test"]
repl = ["dirs", "rustyline", "colored", "prettytable-rs"]
lisp-test = ["colored"]

[dependencies]
lazy_static = "1.4"
fnv = "1.0"

binwrite = "0.2.1"
binread = "2.1.1"

prettytable-rs = { version = "^0.8", optional = true }
dirs = { version = "2.0", optional = true }
rustyline = { version = "6.2", optional = true }
colored = { version = "1.9", optional = true }

## Would be useful to have /inside/ lisp
# regex = "1.3"

## Will be used to dump code
# serde = "1.0.114"

[build-dependencies]
bindgen = "0.53"
cc = "1.0"

[lib]
name = "spaik"
path = "src/lib.rs"

[[bin]]
name = "repl"
path = "src/repl.rs"
required-features = ["repl"]

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "tokenize"
path = "src/bin/tokenize.rs"

[[bin]]
name = "lisp-test"
path = "src/lisp_test.rs"
required-features = ["lisp-test"]

[[bin]]
name = "scratch"
path = "src/scratch.rs"
