[package]
name = "spaik"
version = "0.1.0"
authors = ["Jonas Møller <jonas@nimda.no>"]
description = "A Lisp"
readme = "README.org"
edition = "2018"
repository = "https://github.com/snyball/spaik"
homepage = "https://github.com/snyball/spaik"
license = "BSD-2-Clause"

[profile.release]
# lto = "fat"
panic = "abort"

[features]
default = ["repl", "lisp-test"]
repl = ["colored", "prettytable-rs", "dirs"]
#tables = ["prettytable-rs"]
readline = ["rustyline"]
lisp-test = ["colored"]
#wasm = ["wasm-bindgen"]

[build]
target = "wasm32-unknown-unknown"

[dependencies]
lazy_static = "1.4"
fnv = "1.0"

log = "0.4"
#pretty_env_logger = "0.3"

binwrite = "0.2.1"
binread = "2.1.1"

prettytable-rs = { version = "^0.8", optional = true }
dirs = { version = "4.0.0", optional = true }
rustyline = { version = "6.2", optional = true }
colored = { version = "1.9", optional = true }
#wasm-bindgen = { version = "0.2.79", optional = true }

[build-dependencies]
bindgen = "0.53"
cc = "1.0"

[lib]
name = "spaik"
path = "src/lib.rs"

[[bin]]
name = "repl"
path = "src/bin/readline-repl.rs"
required-features = ["repl", "rustyline"]

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "tokenize"
path = "src/bin/tokenize.rs"

[[bin]]
name = "lisp-test"
path = "src/lisp_test.rs"
required-features = ["lisp-test"]

[[bin]]
name = "scratch"
path = "src/scratch.rs"

[[bin]]
name = "spaikc"
path = "src/spaikc.rs"

[[bin]]
name = "wasm-repl"
path = "src/bin/wasm-repl.rs"
required-features = ["repl"]
