[toolchain]
channel = "nightly-2025-08-04"
components = [ "rustfmt", "clippy", "rust-src", "rust-docs", "rust-analyzer", "rustc-codegen-cranelift-preview", "miri" ]
targets = [ "x86_64-unknown-linux-gnu", "x86_64-unknown-linux-musl", "wasm32-unknown-unknown", "wasm32-wasip1" ]
