[toolchain]
channel = "1.84.1"
components = [ "clippy", "rust-analyzer" ]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "x86_64-pc-windows-gnu",
    "wasm32-wasip1",
    "wasm32-unknown-unknown"
]