[toolchain]
channel = "1.85.0"
components = [ "rustfmt", "clippy", "rust-src", "rust-docs", "rust-analyzer" ]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "x86_64-pc-windows-gnu",
    "wasm32-wasip1",
    "wasm32-unknown-unknown"
]