[toolchain]
channel = "nightly-2025-08-04"
components = [ "rustfmt", "clippy", "rust-src", "rust-docs", "rust-analyzer", "rustc-codegen-cranelift-preview" ]
targets = [ "x86_64-unknown-linux-gnu", "wasm32-unknown-unknown" ]
