name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        sudo snap install --edge just --classic
        rustup target add wasm32-wasi
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run tests on wasm
      run: |
        curl https://wasmtime.dev/install.sh -sSf | bash
        just test-wasm
    - uses: actions/checkout@v3
    - name: Install Miri
      run: |
        rustup toolchain install nightly --component miri
        rustup override set nightly
        cargo miri setup
    - name: Test with Miri
      run: cargo miri run --bin lisp-test
      env:
        MIRIFLAGS: "-Zmiri-disable-isolation -Zmiri-tree-borrows"
