name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup
      run: |
        sudo snap install --edge just --classic
        sudo apt install valgrind wine gcc-mingw-w64 binutils-mingw-w64 gcc-i686-linux-gnu binutils-i686-linux-gnu
        rustup target add wasm32-wasi
        rustup target add x86_64-pc-windows-gnu
        rustup target add i686-unknown-linux-gnu
        cargo install cargo-valgrind
    - uses: actions/checkout@v3
    - name: Install Miri
      run: |
        rustup toolchain install nightly --component miri
        cargo +nightly miri setup
    - name: Build
      run: cargo build --verbose
    - name: Run tests on Linux
      run: cargo test --verbose
    # - name: Run tests on 32-bit Linux
    #   run: cargo test --verbose --target i686-unknown-linux-gnu
    - name: Run tests on 32-bit WebAssembly
      run: |
        curl https://wasmtime.dev/install.sh -sSf | bash
        just test-wasm
    - name: Run tests on WINE
      run: cargo test --verbose --target x86_64-pc-windows-gnu
      env:
        CARGO_TARGET_X86_64_PC_WINDOWS_GNU_RUNNER: "wine"
    # - name: Run tests with Valgrind
    #   run: |
    #     export PATH="$PATH:$HOME/.cargo/bin"
    #     cargo valgrind test
    # - name: Run tests with Valgrind 32-bit
    #   run: |
    #     export PATH="$PATH:$HOME/.cargo/bin"
    #     cargo valgrind test --target i686-unknown-linux-gnu
    - name: Run tests on Miri
      run: cargo +nightly miri test
      env:
        MIRIFLAGS: "-Zmiri-disable-isolation -Zmiri-tree-borrows"
    - name: Run tests on Miri 32-Bit
      run: cargo +nightly miri test --target i686-unknown-linux-gnu
      env:
        MIRIFLAGS: "-Zmiri-disable-isolation -Zmiri-tree-borrows"
